[package]
name = "niri_workspaces"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.12"
niri-ipc = "25.8.0" 
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
