[font]
size = 24.0
   
[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
   
[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[scrolling]
history = 10000
