[package]
name = "battery_info"
version = "0.1.0"
edition = "2024"

[dependencies]
battery = "0.7.8"
clap = { version = "4.5.46", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.12"

[dependencies.eww]
path = "../eww"
